### ISSUE TITLE
Customising the DevOps Stack

### ISSUE THREAD

**Issue by cloudcompute** [camptocamp/devops-stack#1000]
Hi DevOps Team

Yesterday I had stumbled upon this repository. Looks like it is a great work. I have some questions in this regard.

a. How can I customise this stack, for example, `replace Treafik with Nginx`.. Is there any documentation relating to it?

b. How are secrets (like passwords, private keys) getting stored.. `unencrypted in the underlying etcd store`? You are not using something like Hashicorp Vault or any password manager, may I know why is it so. If I want to add Vault, it'd probably involve lot of modifications, could you pl. guide, how can I?

Just curious to know, is there any specific reason to use these:
- Traefik instead of Nginx
- Keycloak instead of other IAMs like Authentik, Authelia
- kind instead of k3d

Do Traefik and Keycloak have an edge over their counterparts?

Thank you.

**Comment by lentidas** [comment]
Hi @cloudcompute  !

First of all, thank you for your interest and happy #1000 issue/PR :tada:

As for your questions:
We have some contributing guidelines on our documentation pages, which are mainly focused to our internal teams and processes. However, probably there is nothing that could help you make the customization you are asking for...

Replacing Traefik with Nginx could be done, **however it would not be a plug-and-play task at the moment, since the other modules of the DevOps Stack that have ingresses depend heavily on Traefik**. This is because they have their ingresses hard-coded with annotations to Traefik, as you can see on [these lines (21-28)](https://github.com/camptocamp/devops-stack-module-keycloak/blob/3c26e41bbc7f7d12318b5a2d82d92a17fa2d3b3a/locals.tf#L21) on the Keycloak module.

As for the reasoning behind each choice:
- **Traefik vs. _something else_** - I was not around when Traefik was chosen, maybe someone else from the team can chime in.
- **Keycloak vs. Authentik, Authelia** - Keycloak was chosen because it was more mature at the time; however we do not really use it in production and we never took that much time to consider it; the important part for the stack is that there is an OpenID Connect provider to use as an authentication backend; Keycloak is mainly used on local development deployments using KinD and on our production deployments we usually use the cloud provider offerings (e.g. Cognito on AWS).
- **KinD vs. _something else_** - this type of deployment is only used for testing and/or learning deployments; we used K3s for a long time but it was painful to configure; finally we opted on KinD for the simplicity and because it is CNCF certified Kubernetes installer.

As for the secrets, everything on the cluster is stored as Kubernetes secrets, so it is unencrypted in the cluster. Support for Hashicorp Vault was not introduced because we try and isolate the clusters of our clients as much as possible and having a centralized Hashicorp Vault in which all clusters depended on was not ideal. Typically we try that most of the secrets intrinsic to the stack itself are dynamically generated with Terraform and the state file is stored on encrypted backends. As for the applications that are deployed on the cluster, we normally load a plugin sidecar to Argo CD that uses an Helm patched with SoPS so we can have the secrets encrypted on our repositories for a seamless GitOps approach. See https://github.com/camptocamp/helm-sops and https://github.com/camptocamp/docker-argocd-cmp-helmfile to have an idea :)

I hope I answered your questions!

**Comment by cloudcompute** [comment]
Hi @lentidas and @vquiby

I really appreciate the response (for the 1000th question) in detail, it has helped me gain insights into the production environment (especially the secrets).

I will take a closer look at the stack's code.

Thank you
